baseURL = "https://marcel.bollmann.me/"
languageCode = "en-us"
title = "Marcel Bollmann"
disableKinds = ["taxonomy", "taxonomyTerm"]

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true
